
export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
export const CHANGE_PROJECTS_DATA = 'CHANGE_PROJECTS_DATA'
export const CHANGE_PROJECTS_ERRORS = 'CHANGE_PROJECTS_ERRORS'
export const TOGGLE_PROJECTS_LOADING = 'TOGGLE_PROJECTS_LOADING'
