
export const CHANGE_TASKS_DATA = 'CHANGE_TASKS_DATA'
export const EDIT_TASK = 'EDIT_TASK'
export const TOGGLE_TASKS_LOADING = 'TOGGLE_TASKS_LOADING'
export const CHANGE_TASKS_ERRORS = 'CHANGE_TASKS_ERRORS'
export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST'
