
export const POST_TOKENS_REQUEST = 'POST_TOKENS_REQUEST'
export const CHANGE_TOKENS_STATUS = 'CHANGE_TOKENS_STATUS'
export const CHANGE_TOKENS_ERRORS = 'CHANGE_TOKENS_ERRORS'
export const TOGGLE_TOKENS_LOADING = 'TOGGLE_TOKENS_LOADING'
export const PUT_TOKENS_REQUEST = 'PUT_TOKENS_REQUEST'
export const REFRESH_TOKEN_WATCH = 'REFRESH_TOKEN_WATCH'
