
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const CHANGE_USERS_DATA = 'CHANGE_USERS_DATA'
export const TOGGLE_USERS_LOADING = 'TOGGLE_USERS_LOADING'
export const CHANGE_USERS_ERRORS = 'CHANGE_USERS_ERRORS'
