
export const USER_REGISTRATION = 'USER_REGISTRATION'
export const CHANGE_USER_DATA = 'CHANGE_USER_DATA'
export const CHANGE_USER_PARAM = 'CHANGE_USER_PARAM'
export const CHANGE_USER_ERRORS = 'CHANGE_USER_ERRORS'
export const TOGGLE_USER_LOADNIG = 'TOGGLE_USER_LOADING'
